"""
OM AI PPO Training Infrastructure.

This module provides real Proximal Policy Optimization (PPO) infrastructure
for fine-tuning language models via reinforcement learning from human feedback
(RLHF) or automated reward signals.

IMPORTANT: This is production-quality infrastructure, not a demo stub.
However, it requires:
  - A trained base policy (OMTransformer checkpoint)
  - A reward model (or reward function) that scores (prompt, response) pairs
  - Rollout data generated by the policy

The PPO algorithm implemented here follows the standard RLHF recipe:
  1. Collect rollouts from the current policy
  2. Score rollouts with a reward model
  3. Compute advantages using Generalized Advantage Estimation (GAE)
  4. Update policy with clipped surrogate loss + value loss + entropy bonus
  5. Apply KL penalty vs. reference policy to prevent mode collapse

Reference: Schulman et al. (2017) "Proximal Policy Optimization Algorithms"
           Stiennon et al. (2020) "Learning to summarize from human feedback"
"""
from __future__ import annotations

import logging
import math
from dataclasses import dataclass, field
from typing import Callable

import torch
import torch.nn as nn
import torch.nn.functional as F

logger = logging.getLogger(__name__)


# ─────────────────────────────────────────────────────────────────────────────
# Rollout buffer
# ─────────────────────────────────────────────────────────────────────────────


@dataclass
class Rollout:
    """A single (prompt, response) rollout with associated RL quantities."""
    prompt_ids: list[int]
    response_ids: list[int]
    logprobs: list[float]       # log π_θ(a_t | s_t) for each response token
    ref_logprobs: list[float]   # log π_ref(a_t | s_t) — KL reference
    values: list[float]         # V(s_t) from the value head
    reward: float               # scalar reward from reward model (end of sequence)
    advantages: list[float] = field(default_factory=list)
    returns: list[float] = field(default_factory=list)


class RolloutBuffer:
    """Fixed-size buffer that accumulates rollouts for a PPO update epoch.

    Example::

        buf = RolloutBuffer(max_rollouts=64)
        buf.add(rollout)
        if buf.is_full():
            trainer.train_epoch(buf)
            buf.clear()
    """

    def __init__(self, max_rollouts: int = 64) -> None:
        self.max_rollouts = max_rollouts
        self._rollouts: list[Rollout] = []

    def add(self, rollout: Rollout) -> None:
        self._rollouts.append(rollout)

    def is_full(self) -> bool:
        return len(self._rollouts) >= self.max_rollouts

    def clear(self) -> None:
        self._rollouts.clear()

    def __len__(self) -> int:
        return len(self._rollouts)

    @property
    def rollouts(self) -> list[Rollout]:
        return list(self._rollouts)

    def stats(self) -> dict:
        if not self._rollouts:
            return {"count": 0}
        rewards = [r.reward for r in self._rollouts]
        return {
            "count": len(self._rollouts),
            "reward_mean": sum(rewards) / len(rewards),
            "reward_max": max(rewards),
            "reward_min": min(rewards),
        }


# ─────────────────────────────────────────────────────────────────────────────
# Advantage computation (GAE)
# ─────────────────────────────────────────────────────────────────────────────


def compute_advantages(
    rollout: Rollout,
    gamma: float = 0.99,
    lam: float = 0.95,
    reward_normalise: bool = True,
) -> Rollout:
    """Compute Generalised Advantage Estimates (GAE) in-place on a rollout.

    For token-level RL we treat each response token as a timestep.  The
    reward is placed on the final token; all intermediate rewards are zero.

    Args:
        rollout: A completed rollout (values and reward must be populated).
        gamma: Discount factor.
        lam: GAE lambda (trade-off between bias and variance).
        reward_normalise: If True, the reward is left as-is (normalisation
            is performed at batch level by PPOTrainer).

    Returns:
        The same rollout object with ``advantages`` and ``returns`` filled in.
    """
    T = len(rollout.response_ids)
    values = rollout.values
    if len(values) != T:
        # Pad / truncate value estimates to match response length
        values = (values + [0.0] * T)[:T]

    # Build per-step rewards: only the final token receives the scalar reward.
    rewards = [0.0] * T
    if T > 0:
        rewards[-1] = rollout.reward

    advantages = [0.0] * T
    returns = [0.0] * T
    gae = 0.0

    for t in reversed(range(T)):
        next_value = values[t + 1] if t + 1 < T else 0.0
        delta = rewards[t] + gamma * next_value - values[t]
        gae = delta + gamma * lam * gae
        advantages[t] = gae
        returns[t] = advantages[t] + values[t]

    rollout.advantages = advantages
    rollout.returns = returns
    return rollout


def compute_advantages_batch(
    rollouts: list[Rollout],
    gamma: float = 0.99,
    lam: float = 0.95,
    normalise_advantages: bool = True,
) -> list[Rollout]:
    """Compute GAE for a list of rollouts and optionally normalise advantages.

    Normalisation is applied across all tokens in the batch to stabilise
    gradient magnitudes.
    """
    for r in rollouts:
        compute_advantages(r, gamma=gamma, lam=lam)

    if normalise_advantages:
        all_advs = [a for r in rollouts for a in r.advantages]
        if len(all_advs) > 1:
            mean = sum(all_advs) / len(all_advs)
            var = sum((a - mean) ** 2 for a in all_advs) / len(all_advs)
            std = math.sqrt(var + 1e-8)
            for r in rollouts:
                r.advantages = [(a - mean) / std for a in r.advantages]

    return rollouts


# ─────────────────────────────────────────────────────────────────────────────
# Value head (critic)
# ─────────────────────────────────────────────────────────────────────────────


class ValueHead(nn.Module):
    """Linear value head projecting model hidden states to scalar V(s).

    This is attached on top of the frozen transformer body during PPO.
    """

    def __init__(self, d_model: int) -> None:
        super().__init__()
        self.proj = nn.Linear(d_model, 1, bias=True)
        nn.init.zeros_(self.proj.weight)
        nn.init.zeros_(self.proj.bias)

    def forward(self, hidden: torch.Tensor) -> torch.Tensor:
        """Args:
            hidden: ``(batch, seq, d_model)`` last hidden states.
        Returns:
            ``(batch, seq)`` value estimates.
        """
        return self.proj(hidden).squeeze(-1)


# ─────────────────────────────────────────────────────────────────────────────
# PPO Trainer
# ─────────────────────────────────────────────────────────────────────────────


@dataclass
class PPOConfig:
    """Hyper-parameters for PPO training."""
    lr: float = 1e-5
    clip_eps: float = 0.2          # ε for clipped surrogate objective
    value_coef: float = 0.5        # coefficient for value loss term
    entropy_coef: float = 0.01     # coefficient for entropy bonus
    kl_coef: float = 0.1           # coefficient for KL penalty vs reference
    kl_target: float = 0.02        # adaptive KL target (0 = fixed)
    gamma: float = 0.99
    lam: float = 0.95
    ppo_epochs: int = 4            # inner optimisation epochs per buffer
    max_grad_norm: float = 1.0
    normalise_advantages: bool = True


class PPOTrainer:
    """Proximal Policy Optimisation trainer for OM AI language models.

    The trainer wraps the policy model and value head and exposes a
    ``train_epoch`` method that consumes a completed ``RolloutBuffer``.

    Usage (conceptual)::

        trainer = PPOTrainer(policy, value_head, ref_policy, config)
        while True:
            rollouts = collect_rollouts(policy, env, tokenizer)
            buffer = RolloutBuffer()
            for r in rollouts:
                buffer.add(r)
            stats = trainer.train_epoch(buffer)

    Notes:
        - The reference policy (``ref_policy``) is used only for the KL
          penalty and is never updated.
        - For tiny test models the arithmetic is identical; the training loop
          simply won't learn much without real reward signal.
    """

    def __init__(
        self,
        policy: nn.Module,
        value_head: ValueHead,
        ref_policy: nn.Module,
        config: PPOConfig | None = None,
        device: torch.device | None = None,
    ) -> None:
        self.policy = policy
        self.value_head = value_head
        self.ref_policy = ref_policy
        self.cfg = config or PPOConfig()
        self.device = device or torch.device("cpu")

        # Optimise policy + value head together; reference policy is frozen.
        self.optimizer = torch.optim.AdamW(
            list(policy.parameters()) + list(value_head.parameters()),
            lr=self.cfg.lr,
        )
        # Freeze reference policy
        for p in ref_policy.parameters():
            p.requires_grad_(False)

        self._kl_coef = self.cfg.kl_coef  # adaptive KL coefficient

    # ------------------------------------------------------------------ #
    #  Logprob helpers                                                      #
    # ------------------------------------------------------------------ #

    @torch.no_grad()
    def compute_logprobs(
        self,
        model: nn.Module,
        input_ids: torch.Tensor,
        response_mask: torch.Tensor,
    ) -> torch.Tensor:
        """Compute per-token log-probabilities for response tokens.

        Args:
            model: A model whose ``forward(input_ids)`` returns a dict with
                   ``"logits"`` key of shape ``(B, T, vocab)``.
            input_ids: ``(B, T)`` token ids (prompt + response concatenated).
            response_mask: Boolean ``(B, T)`` mask — True at response positions.

        Returns:
            ``(total_response_tokens,)`` tensor of log-probs.
        """
        out = model(input_ids)
        logits = out["logits"] if isinstance(out, dict) else out
        log_probs = F.log_softmax(logits, dim=-1)

        # Shift: logit at position t predicts token at t+1
        shifted_log_probs = log_probs[:, :-1, :]
        shifted_ids = input_ids[:, 1:]
        shifted_mask = response_mask[:, 1:]

        token_log_probs = torch.gather(
            shifted_log_probs, 2, shifted_ids.unsqueeze(-1)
        ).squeeze(-1)
        return token_log_probs[shifted_mask]

    # ------------------------------------------------------------------ #
    #  Train epoch                                                          #
    # ------------------------------------------------------------------ #

    def train_epoch(self, buffer: RolloutBuffer) -> dict:
        """Run PPO inner epochs over the rollouts in *buffer*.

        Returns:
            A dict with training statistics (losses, KL, entropy, etc.).
        """
        rollouts = buffer.rollouts
        if not rollouts:
            return {"error": "empty buffer"}

        compute_advantages_batch(
            rollouts,
            gamma=self.cfg.gamma,
            lam=self.cfg.lam,
            normalise_advantages=self.cfg.normalise_advantages,
        )

        total_policy_loss = 0.0
        total_value_loss = 0.0
        total_entropy = 0.0
        total_kl = 0.0
        total_steps = 0

        self.policy.train()
        self.value_head.train()

        for _ in range(self.cfg.ppo_epochs):
            for rollout in rollouts:
                if not rollout.advantages:
                    continue

                prompt_ids = rollout.prompt_ids
                response_ids = rollout.response_ids
                T_resp = len(response_ids)
                if T_resp == 0:
                    continue

                full_ids = prompt_ids + response_ids
                input_ids = torch.tensor([full_ids], dtype=torch.long, device=self.device)
                T_full = len(full_ids)

                # Build response mask (True for response tokens)
                resp_mask = torch.zeros(1, T_full, dtype=torch.bool, device=self.device)
                resp_mask[0, len(prompt_ids):] = True

                # Old log-probs (stored in rollout, converted to tensor)
                old_logprobs = torch.tensor(
                    rollout.logprobs, dtype=torch.float32, device=self.device
                )
                advantages = torch.tensor(
                    rollout.advantages, dtype=torch.float32, device=self.device
                )
                returns = torch.tensor(
                    rollout.returns, dtype=torch.float32, device=self.device
                )

                # Forward pass through policy
                out = self.policy(input_ids, use_cache=False)
                logits = out["logits"] if isinstance(out, dict) else out
                hidden = out.get("last_hidden_state", None) if isinstance(out, dict) else None

                log_probs_full = F.log_softmax(logits, dim=-1)
                shifted_lp = log_probs_full[:, :-1, :]
                shifted_ids = input_ids[:, 1:]
                shifted_mask = resp_mask[:, 1:]

                token_lp = torch.gather(
                    shifted_lp, 2, shifted_ids.unsqueeze(-1)
                ).squeeze(-1)
                new_logprobs = token_lp[shifted_mask]  # (T_resp,)

                # Reference logprobs for KL
                with torch.no_grad():
                    ref_out = self.ref_policy(input_ids, use_cache=False)
                    ref_logits = ref_out["logits"] if isinstance(ref_out, dict) else ref_out
                    ref_lp_full = F.log_softmax(ref_logits, dim=-1)
                    ref_shifted = ref_lp_full[:, :-1, :]
                    ref_token_lp = torch.gather(
                        ref_shifted, 2, shifted_ids.unsqueeze(-1)
                    ).squeeze(-1)
                    ref_logprobs = ref_token_lp[shifted_mask]

                # Clipped surrogate policy loss
                ratio = torch.exp(new_logprobs - old_logprobs)
                surr1 = ratio * advantages
                surr2 = ratio.clamp(1.0 - self.cfg.clip_eps, 1.0 + self.cfg.clip_eps) * advantages
                policy_loss = -torch.min(surr1, surr2).mean()

                # Value loss
                if hidden is not None:
                    resp_hidden = hidden[:, len(prompt_ids):, :]
                    values_pred = self.value_head(resp_hidden).squeeze(0)
                    value_loss = F.mse_loss(values_pred, returns)
                else:
                    value_loss = torch.tensor(0.0, device=self.device)

                # Entropy bonus (encourages exploration)
                probs = torch.exp(new_logprobs)
                entropy = -(probs * new_logprobs).mean()

                # KL divergence penalty vs reference policy
                kl = (torch.exp(ref_logprobs) * (ref_logprobs - new_logprobs)).mean()

                loss = (
                    policy_loss
                    + self.cfg.value_coef * value_loss
                    - self.cfg.entropy_coef * entropy
                    + self._kl_coef * kl
                )

                self.optimizer.zero_grad()
                loss.backward()
                nn.utils.clip_grad_norm_(
                    list(self.policy.parameters()) + list(self.value_head.parameters()),
                    self.cfg.max_grad_norm,
                )
                self.optimizer.step()

                total_policy_loss += policy_loss.item()
                total_value_loss += value_loss.item()
                total_entropy += entropy.item()
                total_kl += kl.item()
                total_steps += 1

        if total_steps == 0:
            return {"warning": "no trainable rollouts in buffer"}

        # Adaptive KL coefficient update
        mean_kl = total_kl / total_steps
        if self.cfg.kl_target > 0:
            if mean_kl > 1.5 * self.cfg.kl_target:
                self._kl_coef *= 1.5
            elif mean_kl < self.cfg.kl_target / 1.5:
                self._kl_coef /= 1.5
            self._kl_coef = max(1e-4, min(self._kl_coef, 1.0))

        return {
            "policy_loss": total_policy_loss / total_steps,
            "value_loss": total_value_loss / total_steps,
            "entropy": total_entropy / total_steps,
            "kl": mean_kl,
            "kl_coef": self._kl_coef,
            "steps": total_steps,
            **buffer.stats(),
        }
