from __future__ import annotations

from om_ai.core.intelligence import capability_router as router


def test_native_synthesize_uses_om_native_chat(monkeypatch):
    calls = {}

    class FakeNative:
        def chat(self, messages, **kwargs):
            calls["messages"] = messages
            calls["kwargs"] = kwargs
            return "Use a bounded retry policy and exponential backoff for transient failures."

    monkeypatch.setattr("om_ai.backends.om_native.OMNativeBackend", FakeNative)
    result = router._native_synthesize(
        "How should retries work?",
        "research",
        {"project_hint": "Python API client"},
        {"intent": "question"},
        tool_text="The service returns HTTP 503 for temporary overload.",
    )
    assert result.startswith("Use a bounded retry policy")
    assert any(m["role"] == "system" and "OM's own native model weights" in m["content"] for m in calls["messages"])
    assert "HTTP 503" in calls["messages"][-1]["content"]
    assert calls["kwargs"]["max_new_tokens"] >= 64


def test_native_synthesize_rejects_static_stub(monkeypatch):
    class FakeNative:
        def chat(self, messages, **kwargs):
            return "Here's a clear take: define the outcome and break it into actionable steps."

    monkeypatch.setattr("om_ai.backends.om_native.OMNativeBackend", FakeNative)
    assert router._native_synthesize(
        "Help me implement retries", "coding", {}, {}
    ) == ""


def test_native_only_capability_failure_does_not_return_canned_handler(monkeypatch):
    monkeypatch.setattr(router, "_native_synthesize", lambda *args, **kwargs: "")
    monkeypatch.setattr(router, "_cap_research", lambda *args, **kwargs: "Here is a clear useful answer grounded in the request.")
    result = router.CapabilityRouter().execute(
        {"capability": "research", "handler": router._cap_research},
        "Explain a topic",
        {},
        {},
    )
    assert "native model could not produce" in result.lower()

def test_short_hinglish_chat_uses_compact_native_prompt(monkeypatch):
    calls = {}

    class FakeNative:
        def chat(self, messages, **kwargs):
            calls["messages"] = messages
            calls["kwargs"] = kwargs
            return "Haan Rohit, bilkul! Hum baat kar sakte hain. Batao, kya chal raha hai?"

    monkeypatch.setattr("om_ai.backends.om_native.OMNativeBackend", FakeNative)
    result = router._native_synthesize(
        "kya hum bat kar sakte ha",
        "chat",
        {},
        {"intent": "conversation"},
    )
    assert result.startswith("Haan Rohit")
    assert len(calls["messages"][0]["content"]) < 350
    assert calls["kwargs"]["max_new_tokens"] <= 64
    assert calls["kwargs"]["min_new_tokens"] == 1

def test_chat_clarify_and_prompt_handlers_delegate_to_native_model(monkeypatch):
    calls = []

    def fake_synthesize(question, capability, context, understanding, **kwargs):
        calls.append((question, capability, context, understanding))
        return f"Native answer for {capability}"

    monkeypatch.setattr(router, "_native_synthesize", fake_synthesize)

    assert router._cap_chat("hello", {}, {}).strip() == "Native answer for chat"
    assert router._cap_clarify("what do you mean?", {}, {}).strip() == "Native answer for clarify"
    assert router._cap_prompt("write a prompt for an API", {}, {}).strip() == "Native answer for prompt_generator"
    assert [call[1] for call in calls] == ["chat", "clarify", "prompt_generator"]


def test_coding_execution_does_not_use_static_handler_as_native_draft(monkeypatch):
    monkeypatch.setenv("OM_CAPABILITY_NATIVE_GENERATION", "1")

    def forbidden_handler(*args, **kwargs):
        raise AssertionError("Coding handler must not run before native synthesis")

    monkeypatch.setattr(router, "_cap_coding", forbidden_handler)
    monkeypatch.setattr(router, "_native_synthesize", lambda *args, **kwargs: "Native code solution")

    result = router.CapabilityRouter().execute(
        {"capability": "coding", "handler": forbidden_handler},
        "Write a Python retry helper",
        {},
        {"intent": "code_creation"},
    )
    assert result.strip() == "Native code solution"

def test_all_text_capability_handlers_use_native_synthesis(monkeypatch):
    calls = []

    def fake_synthesize(question, capability, context, understanding, **kwargs):
        calls.append(capability)
        return f"Generated by native OM for {capability}"

    monkeypatch.setattr(router, "_native_synthesize", fake_synthesize)
    handlers = [
        (router._cap_chat, "chat"),
        (router._cap_clarify, "clarify"),
        (router._cap_prompt, "prompt_generator"),
        (router._cap_recommendation, "recommendation"),
        (router._cap_coding, "coding"),
        (router._cap_research, "research"),
        (router._cap_planning, "planning"),
        (router._cap_analysis, "analysis"),
    ]
    for handler, capability in handlers:
        assert handler("Do this task", {}, {}).strip() == f"Generated by native OM for {capability}"
    assert calls == [capability for _, capability in handlers]

