"""Companion realtime event type constants."""
from __future__ import annotations

class EventType:
    COMPANION_STATE = "companion.state"
    VOICE_WAKE = "voice.wake"
    VOICE_SPEECH_STARTED = "voice.speech_started"
    VOICE_SPEECH_ENDED = "voice.speech_ended"
    STT_PARTIAL = "stt.partial"
    STT_FINAL = "stt.final"
    BRAIN_STARTED = "brain.started"
    BRAIN_ACTIVITY = "brain.activity"
    ACTION_PLANNED = "action.planned"
    PERMISSION_REQUIRED = "permission.required"
    PERMISSION_RESOLVED = "permission.resolved"
    ACTION_STARTED = "action.started"
    ACTION_COMPLETED = "action.completed"
    ACTION_FAILED = "action.failed"
    RESPONSE_DELTA = "response.delta"
    TTS_STARTED = "tts.started"
    TTS_AUDIO = "tts.audio"
    TTS_COMPLETED = "tts.completed"
    AVATAR_STATE = "avatar.state"
    RUNTIME_ERROR = "runtime.error"
